version: '3.6'

services:

  todomvc-front-app:
    build:
      context: .
      dockerfile: docker-conf/Dockerfile
      target: base
    depends_on:
      - todobackend-app
    command: npm run start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

    stdin_open: true

  todobackend-app:
    image: jbarroso/todobackend-django
    expose:
      - 8000
    ports:
      - 8000:8000
