version: '3.6'

services:

  todomvc-front-storybook:
    build:
      context: .
      dockerfile: docker-conf/Dockerfile
      target: base
    command: npm run storybook
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 9009
    ports:
      - 9009:9009
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
