version: '3.6'

services:

  cypress:
    image: cypress/included:4.9.0
    depends_on:
      - todomvc-front-app
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://todomvc-front-app:3000
      # share the current folder as volume to avoid copying
    working_dir: /e2e
    volumes:
      - ./:/e2e
