export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE';

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';

export const SAVE_TODO_REQUEST = 'SAVE_TODO_REQUEST';
export const SAVE_TODO_SUCCESS = 'SAVE_TODO_SUCCESS';
export const SAVE_TODO_FAILURE = 'SAVE_TODO_FAILURE';

export const COMPLETE_TODO_REQUEST = 'COMPLETE_TODO_REQUEST';
export const COMPLETE_TODO_SUCCESS = 'COMPLETE_TODO_SUCCESS';
export const COMPLETE_TODO_FAILURE = 'COMPLETE_TODO_FAILURE';

export const COMPLETE_ALL_TODOS_REQUEST = 'COMPLETE_ALL_TODOS_REQUEST';
export const COMPLETE_ALL_TODOS_SUCCESS = 'COMPLETE_ALL_TODOS_SUCCESS';
export const COMPLETE_ALL_TODOS_FAILURE = 'COMPLETE_ALL_TODOS_FAILURE';

export const CLEAR_COMPLETED_REQUEST = 'CLEAR_COMPLETED_REQUEST';
export const CLEAR_COMPLETED_SUCCESS = 'CLEAR_COMPLETED_SUCCESS';
export const CLEAR_COMPLETED_FAILURE = 'CLEAR_COMPLETED_FAILURE';
