name: TodoMVC React
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: docker-compose -f docker-compose.yml -f cypress/docker-compose-cypress.yml up --exit-code-from cypress
